language: node_js
sudo: required
dist: bionic
group: deprecated-2017Q
addons:
  chrome: stable
node_js:
  - "14.17.06"
cache:
  directories:
    - node_modules
before_install:
 - npm install -g grunt-cli
before_script:
 - npm install
 - grunt build buildsite --no-hardlink